# Generated by Django 4.0.4 on 2022-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
